name: Fetch and Publish News

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
 #   - cron: '0 6 * * *'  # Se ejecuta diariamente a las 6 AM UTC
    - cron: '0 0 * * *'  # Ejecutar una vez al día a medianoche
  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write  # Agregar esto si ves errores relacionados con id-token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed dependencies
      run: |
        pip show pandas
        pip show requests 
        pip show beautifulsoup4 
        pip show google-cloud-translate 
        pip show pytest
        pip show feedparser
        


    - name: Run unit tests
      run: |
        pytest Tests

    - name: Fetch news and translate
      run: python .github/workflows/scripts/fetch_news.py
   
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_branch: gh-pages
       publish_dir: ./docs
       artifact_name: unique-github-pages-artifact
