name: Fetch and Publish News

on:
  schedule:
    - cron: '0 6 * * *'  # Se ejecuta diariamente a las 6 AM UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed dependencies
      run: |
        pip show pandas
        pip show requests 
        pip show beautifulsoup4 
        pip show google-cloud-translate 
        pip show pytest
        pip show feedparser
        


    - name: Run unit tests
      run: |
        pytest Tests

    - name: Fetch news and translate
      run: python .github/workflows/scripts/fetch_news.py
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Commit changes
      run: |   
        git add docs/index.html
        git commit -m 'Update news'
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN.repo }}
      run: | 
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN.repo }}@github.com/${{ github.repository }}
        git push origin main
    