name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Se ejecuta diariamente a las 6 AM UTC
  workflow_dispatch:  # Habilitar ejecuciones manuales

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch news and generate HTML
      #run: python .github/workflows/scripts/fetch_news.py
      run: python .github/workflows/scripts/feed8.py
    - name: List contents of ./docs
      run: ls -la ./docs  
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
